language: cpp

sudo: required
dist: trusty

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -qq cmake qt5-default

before_script:
  - mkdir build
  - cd build
  - cmake -DOPTION_BUILD_EXAMPLES=On ..

script:
  - make -j8
  - make test
