[package]
name = "metacall-inline"
version = "0.2.0"
repository = "https://github.com/metacall/core/tree/develop/source/ports/rs_port"
edition = "2021"
license = "Apache-2.0"
description = "Inline macros for metacall crate."

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0.36", features = ["span-locations"] }
quote = "1.0.14"
