[package]
name = "inline"
version = "0.1.0"
edition = "2021"

[lib]
proc_macro = true

[dependencies]
proc-macro2 = { version = "1.0.34", features = ["span-locations"] }
abi = { path = "../abi" }
quote = "1.0.10"
