workspace = { members = ["crates/metacall-bindings"] }
[package]
name = "metacall-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
metacall-bindings = { path = "crates/metacall-bindings" }
