edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"

imports_granularity = "Crate"
group_imports = "StdExternalCrate"

fn_args_layout = "Tall"
brace_style = "SameLineWhere"

match_arm_blocks = true
match_block_trailing_comma = true

control_brace_style = "AlwaysSameLine"

use_small_heuristics = "Default"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true

wrap_comments = false
normalize_comments = false
normalize_doc_attributes = false

struct_lit_single_line = true
indent_style = "Block"

error_on_line_overflow = false
error_on_unformatted = false

trailing_comma = "Vertical"
trailing_semicolon = true

chain_width = 60
single_line_if_else_max_width = 50
