[package]
name = "metacall-sys"
version = "0.1.4"
repository = "https://github.com/metacall/core/tree/develop/source/ports/rs_port/sys"
keywords = ["ffi", "bindings", "metacall"]
edition = "2021"
license = "Apache-2.0"
description = "Crate for finding metacall library in the system."

[lib]
crate-type = ["lib"]
doctest = false
name = "metacall_sys"
path = "src/lib.rs"
