[package]
name = "metacall-sys"
version = "0.1.2"
repository = "https://github.com/metacall/core/tree/develop/source/ports/rs_port/sys"
keywords = ["ffi", "bindings", "metacall"]
edition = "2021"
license = "Apache-2.0"
description = "Crate for finding metacall library in the system."
